name: Android CI

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: ${{ runner.OS }}-gradle-cache

      - name: Gradle Wraper Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: ${{ runner.OS }}-gradle-wraper-cache

      - name: Android Build Cache
        uses: actions/cache@v1
        with:
          path: ~/.android/build-cache
          key: ${{ runner.OS }}-android-cache

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Sync Gradle
        run: ./gradlew clean dependencies

      - name: Build the project
        run: ./gradlew build

      - name: Test
        run: ./gradlew testDebugUnitTest