name: Android CI

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Sync Gradle
        run: ./gradlew clean dependencies

      - name: Build the project
        run: ./gradlew build

      - name: Test
        run: ./gradlew testDebugUnitTest